# 仮想化するベースOS
FROM ubuntu:18.04
# 誰が作ったかは入れておきましょう
LABEL maintainer="amano123"

# 各環境変数を設定
ENV USER "amano"
ENV HOME /home/${USER}
ENV DEBCONF_NOWARNINGS yes
ENV SHELL /usr/bin/zsh
ENV UBUNTU_CONTAINER_NAME ubuntu18.04_02

# 設定ファイルをコピー
## python
COPY ./python3/library/library.txt /

# サーバーを日本のサーバーに変更
RUN sed -i 's@archive.ubuntu.com@ftp.jaist.ac.jp/pub/Linux@g' /etc/apt/sources.list

RUN set -x \
&&  apt-get update -y\
&&  apt upgrade -y --no-install-recommends\
&&  apt-get install -y --no-install-recommends \
                sudo \
		zsh \
                vim \
                git \
		wget \
		curl \
		build-essential \
		cmake \
		gcc \
		libboost-dev \
                ## python3 
                python3 \
                python3-pip \
                iputils-ping \
                ## network
                net-tools \
                ## japanese
                language-pack-ja-base \
                language-pack-ja \

# python3 → python
&&  ln -s /usr/bin/python3 /usr/bin/python \
# pip3 → pip
&&  ln -s /usr/bin/pip3 /usr/bin/pip \
&&  apt-get -y clean \
&&  rm -rf /var/lib/apt/lists/* \
# 日本語化
&&  locale-gen ja_JP.UTF-8 \
# USER
## 一般ユーザーアカウントを追加
&& useradd -m ${USER} \
## 一般ユーザーにsudo権限を付与
&&  gpasswd -a ${USER} sudo \
## 一般ユーザーのパスワード設定
&&  echo "${USER}:0000" | chpasswd \
## sudo passを無くす
&&  echo "${USER} ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/$USER \
# Pythonのライブラリ追加
&&  python3 -m pip --no-cache-dir install --upgrade pip \
&&  pip3 --no-cache-dir install -I setuptools \
&&  python3 -m pip --no-cache-dir install --upgrade tensorflow nodejs elasticsearch six pyknp sklearn \
&&  pip3 --no-cache-dir install -Ir /library.txt \
&&  rm -rf /library.txt

#jumannp
RUN wget https://github.com/ku-nlp/jumanpp/releases/download/v2.0.0-rc2/jumanpp-2.0.0-rc2.tar.xz \
&& tar xf jumanpp-2.0.0-rc2.tar.xz \
&& cd ./jumanpp-2.0.0-rc2 \
&& mkdir bld \
&& cd bld \
&& cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./Juman++ \
&& make install -j

RUN touch /etc/ld.so.conf \
&& echo include /usr/local/lib > /etc/ld.so.conf \
&& ldconfig

#pyknp
RUN wget http://nlp.ist.i.kyoto-u.ac.jp/nl-resource/knp/pyknp-0.3.tar.gz \
&& tar -zxvf pyknp-0.3.tar.gz \
#RUN cd pyknp-03 \
#	&& python setup.py install
&& rm -rf pyknp-0.3.tar.gz juman-7.01.tar.xz

#SVM_perf
RUN wget http://download.joachims.org/svm_perf/current/svm_perf.tar.gz \ 
&& mkdir svm_perf \
&& tar zxvf svm_perf.tar.gz -C svm_perf \
&& cd svm_perf \
	&& make \
	&& cp svm_perf_classify /usr/local/bin \
	&& cp svm_perf_learn /usr/local/bin

## zsh
COPY .zshrc ${HOME}

# 以降のRUN/CMDを実行するユーザー
USER ${USER}

# 以降の作業ディレクトリを指定
WORKDIR ${HOME}

CMD ["/bin/zsh"]

